- name: variable preference
  hosts: localhost
  vars:
    WISHES: "Morning from play level variables"
  # vars_files:
  # - var.yaml
  # vars_prompt:
  # - name: WISHES
  #   prompt: "Plaese enter wishes"
  #   private: false
  tasks:
  - name: print wishes"
    # vars:
    #   WISHES: "Morning from Task level variables"
    ansible.builtin.debug:
      msg: "{{WISHES}}"