- name: Install packages using loop
  hosts: localhost
  become: yes
  tasks:
  - name: Instal packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
